---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: validator-src
run:
  path: validator-src/ci/tasks/cleanup.sh
params:
  BOSH_OPENSTACK_DOMAIN_NAME:          replace-me
  BOSH_OPENSTACK_AUTH_URL:             replace-me
  BOSH_OPENSTACK_USERNAME:             replace-me
  BOSH_OPENSTACK_API_KEY:              replace-me
  BOSH_OPENSTACK_PROJECT:              replace-me
  BOSH_OPENSTACK_CA_CERT:              replace-me
  BOSH_OPENSTACK_INTERFACE:            replace-me
